from __future__ import annotations
import json
from pathlib import Path
from typing import Any, Dict, List


def _comment_for_result(r: Dict[str, Any]) -> str:
    text = r.get("text", "")
    kind = "OBFUSCATE_STRING"
    cls = r.get("classification")
    if cls and cls != "user_literal":
        kind = f"Obfusk8:{cls}"
    prefix = "L" if r.get("text_type") == "wchar" else ""
    meta = []
    if r.get("source_strategy"):
        meta.append(f"source={r.get('source_strategy')}")
    if r.get("key_status"):
        meta.append(f"key={r.get('key_status')}")
    suffix = f" [{' ; '.join(meta)}]" if meta else ""
    return f'{kind} -> {prefix}"{text}"{suffix}'


def filtered_results(
    report: Dict[str, Any], *, include_runtime: bool = False
) -> List[Dict[str, Any]]:
    results = report.get("strings", {}).get("results", [])
    out: List[Dict[str, Any]] = []
    for r in results:
        if not r.get("text"):
            continue
        if not include_runtime and r.get("filtered_by_default"):
            continue
        out.append(r)
    return out


def comment_lines(
    report: Dict[str, Any], *, include_runtime: bool = False
) -> List[str]:
    return [
        f"{r.get('call_addr')} ; {_comment_for_result(r)}"
        for r in filtered_results(report, include_runtime=include_runtime)
    ]


def write_comments(
    report: Dict[str, Any], path: str, *, include_runtime: bool = False
) -> None:
    lines = comment_lines(report, include_runtime=include_runtime)
    Path(path).write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def write_ida_script(
    report: Dict[str, Any], path: str, *, include_runtime: bool = False
) -> None:
    entries = []
    for idx, r in enumerate(filtered_results(report, include_runtime=include_runtime)):
        try:
            ea = int(str(r.get("call_addr")), 16)
        except Exception:
            continue
        entries.append(
            {
                "ea": ea,
                "text": r.get("text", ""),
                "comment": _comment_for_result(r),
                "name": f"deobfusk8_str_{idx:04d}",
            }
        )
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    script = f'# Auto-generated by Deobfusk8. Run inside IDA Python.\nimport ida_bytes\nimport ida_name\n\nENTRIES = {body}\n\nfor item in ENTRIES:\n    ea = int(item["ea"])\n    cmt = item["comment"]\n    ida_bytes.set_cmt(ea, cmt, 0)\n    ida_bytes.set_cmt(ea, cmt, 1)\n    try:\n        ida_name.set_name(ea, item["name"], ida_name.SN_CHECK | ida_name.SN_NOWARN)\n    except Exception:\n        pass\n\nprint(f"[Deobfusk8] annotated {{len(ENTRIES)}} call-site(s)")\n'
    Path(path).write_text(script, encoding="utf-8")


def write_ghidra_script(
    report: Dict[str, Any], path: str, *, include_runtime: bool = False
) -> None:
    entries = []
    for idx, r in enumerate(filtered_results(report, include_runtime=include_runtime)):
        try:
            ea = int(str(r.get("call_addr")), 16)
        except Exception:
            continue
        entries.append(
            {
                "ea": ea,
                "text": r.get("text", ""),
                "comment": _comment_for_result(r),
                "label": f"deobfusk8_str_{idx:04d}",
            }
        )
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    script = f'# Auto-generated by Deobfusk8. Run inside Ghidra Script Manager as Python/Jython.\nfrom ghidra.program.model.listing import CodeUnit\nfrom ghidra.program.model.symbol import SourceType\n\nENTRIES = {body}\n\naddr_space = currentProgram.getAddressFactory().getDefaultAddressSpace()\nlisting = currentProgram.getListing()\nsymbol_table = currentProgram.getSymbolTable()\n\nfor item in ENTRIES:\n    addr = addr_space.getAddress(hex(int(item["ea"])))\n    cu = listing.getCodeUnitAt(addr)\n    if cu is not None:\n        cu.setComment(CodeUnit.EOL_COMMENT, item["comment"])\n        cu.setComment(CodeUnit.REPEATABLE_COMMENT, item["comment"])\n    try:\n        symbol_table.createLabel(addr, item["label"], SourceType.USER_DEFINED)\n    except Exception:\n        pass\n\nprint("[Deobfusk8] annotated %d call-site(s)" % len(ENTRIES))\n'
    Path(path).write_text(script, encoding="utf-8")


__all__ = [
    "filtered_results",
    "comment_lines",
    "write_comments",
    "write_ida_script",
    "write_ghidra_script",
]
