from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List


def _comment_for_result(entry: Dict[str, Any]) -> str:
    text = entry.get("text", "")
    kind = "OBFUSCATE_STRING"
    classification = entry.get("classification")
    if classification and classification != "user_literal":
        kind = f"Obfusk8:{classification}"
    wide_prefix = "L" if entry.get("text_type") == "wchar" else ""
    meta: List[str] = []
    if entry.get("source_strategy"):
        meta.append(f"source={entry.get('source_strategy')}")
    if entry.get("key_status"):
        meta.append(f"key={entry.get('key_status')}")
    suffix = f" [{' ; '.join(meta)}]" if meta else ""
    return f'{kind} -> {wide_prefix}"{text}"{suffix}'


def filtered_results(
    report: Dict[str, Any], *, include_runtime: bool = False
) -> List[Dict[str, Any]]:
    results = report.get("strings", {}).get("results", [])
    visible_strings: List[Dict[str, Any]] = []
    for entry in results:
        if not entry.get("text"):
            continue
        if not include_runtime and entry.get("filtered_by_default"):
            continue
        visible_strings.append(entry)
    return visible_strings


def comment_lines(
    report: Dict[str, Any], *, include_runtime: bool = False
) -> List[str]:
    return [
        f"{entry.get('call_addr')} ; {_comment_for_result(entry)}"
        for entry in filtered_results(report, include_runtime=include_runtime)
    ]


def write_comments(
    report: Dict[str, Any], path: str, *, include_runtime: bool = False
) -> None:
    lines = comment_lines(report, include_runtime=include_runtime)
    Path(path).write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def write_ida_script(
    report: Dict[str, Any], path: str, *, include_runtime: bool = False
) -> None:
    entries = []
    for idx, entry in enumerate(
        filtered_results(report, include_runtime=include_runtime)
    ):
        try:
            ea = int(str(entry.get("call_addr")), 16)
        except (TypeError, ValueError):
            continue
        entries.append(
            {
                "ea": ea,
                "text": entry.get("text", ""),
                "comment": _comment_for_result(entry),
                "name": f"deobfusk8_str_{idx:04d}",
            }
        )
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    script = f"""# Generated by Deobfusk8. Run inside IDA Python.
import ida_bytes
import ida_name

ENTRIES = {body}

for entry in ENTRIES:
    ea = int(entry["ea"])
    comment = entry["comment"]
    ida_bytes.set_cmt(ea, comment, 0)
    ida_bytes.set_cmt(ea, comment, 1)
    try:
        ida_name.set_name(ea, entry["name"], ida_name.SN_CHECK | ida_name.SN_NOWARN)
    except Exception as exc:
        print(f"[Deobfusk8] label skipped at {{ea:#x}}: {{exc}}")

print(f"[Deobfusk8] annotated {{len(ENTRIES)}} call-site(s)")
"""
    Path(path).write_text(script, encoding="utf-8")


def write_ghidra_script(
    report: Dict[str, Any], path: str, *, include_runtime: bool = False
) -> None:
    entries = []
    for idx, entry in enumerate(
        filtered_results(report, include_runtime=include_runtime)
    ):
        try:
            ea = int(str(entry.get("call_addr")), 16)
        except (TypeError, ValueError):
            continue
        entries.append(
            {
                "ea": ea,
                "text": entry.get("text", ""),
                "comment": _comment_for_result(entry),
                "label": f"deobfusk8_str_{idx:04d}",
            }
        )
    body = json.dumps(entries, indent=2, ensure_ascii=False)
    script = f"""# Generated by Deobfusk8. Run inside Ghidra Script Manager as Python/Jython.
from ghidra.program.model.listing import CodeUnit
from ghidra.program.model.symbol import SourceType

ENTRIES = {body}

addr_space = currentProgram.getAddressFactory().getDefaultAddressSpace()
listing = currentProgram.getListing()
symbol_table = currentProgram.getSymbolTable()

for entry in ENTRIES:
    addr = addr_space.getAddress(hex(int(entry["ea"])))
    code_unit = listing.getCodeUnitAt(addr)
    if code_unit is not None:
        code_unit.setComment(CodeUnit.EOL_COMMENT, entry["comment"])
        code_unit.setComment(CodeUnit.REPEATABLE_COMMENT, entry["comment"])
    try:
        symbol_table.createLabel(addr, entry["label"], SourceType.USER_DEFINED)
    except Exception as exc:
        print("[Deobfusk8] label skipped at %s: %s" % (addr, exc))

print("[Deobfusk8] annotated %d call-site(s)" % len(ENTRIES))
"""
    Path(path).write_text(script, encoding="utf-8")


__all__ = [
    "filtered_results",
    "comment_lines",
    "write_comments",
    "write_ida_script",
    "write_ghidra_script",
]
